#!/bin/sh
# This file is autogenerated by script_gen.py
# Do not modify this file directly.
apt-add-repository -y ppa:benoit.pierre/plover
apt-add-repository -y ppa:deadsnakes/ppa
apt-add-repository -y ppa:fish-shell/release-3
apt-add-repository -y ppa:git-core/ppa
apt-add-repository -y ppa:longsleep/golang-backports
apt-add-repository -y ppa:neovim-ppa/stable
apt-add-repository -y ppa:pi-rho/dev
apt-get update -y
apt-get install -y\
    curl\
    fish\
    git\
    golang-go\
    jq\
    libevent-dev\
    libncurses-dev\
    neovim\
    plover\
    python-dev\
    python-setuptools\
    python-software-properties\
    python3-dev\
    python3-virtualenv\
    python3.6-dev\
    python3.7-dev\
    ruby-dev\
    software-properties-common\
    vim-gtk
apt-get upgrade -y
apt autoremove -y